version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: client_frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production